stages:
    - install test dependencies
    - test

.test-rules:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# install test dependencies

composer install:
    extends:
        - .test-rules
    stage: install test dependencies

    tags: [ docker ]
    image: registry.miem.hse.ru/kaa-framework/kaa/php:1.0.0

    script:
        - composer install --no-interaction

    artifacts:
        paths:
            - vendor
            - var

# test

PHPStan:
    stage: test
    extends:
        - .test-rules

    tags: [ docker ]
    image: registry.miem.hse.ru/kaa-framework/kaa/php:1.0.0

    script:
        - vendor/bin/phpstan --configuration=fixer/phpstan.neon --no-progress --error-format=gitlab > phpstan.json

    artifacts:
        reports:
            codequality: phpstan.json


Easy Coding Standard:
    stage: test
    extends:
        - .test-rules

    tags: [ docker ]
    image: registry.miem.hse.ru/kaa-framework/kaa/php:1.0.0

    script:
        - vendor/bin/ecs check --config=fixer/ecs.php


Pest:
    stage: test
    extends:
        - .test-rules

    tags: [ docker ]
    image: registry.miem.hse.ru/kaa-framework/kaa/php:1.0.0
    script:
        - php vendor/bin/pest -c fixer/phpunit.xml.dist --parallel --compact --log-junit phpunit-report.xml --colors=never

    artifacts:
        when: always
        reports:
            junit: phpunit-report.xml
